import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ToastContainer from "@/components/provider/ToastProvider";
import LoadingProvider from "@/components/provider/LoadingProvider";
import { CookiesProvider } from "next-client-cookies/server";

export const metadata: Metadata = {
  title: "cher1sh-next-app",
  description: "Generated by cher1sh-next-app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false
  },
};

const pretendard = localFont({
  src: "../fonts/pretendard.woff2",
  variable: "--font-prendard",
  weight: "100 900",
  display: "swap",
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
      </head>
      <body className={`${pretendard.variable} antialiased`}>
        <ToastContainer />
        <LoadingProvider color="#FF582A" />
        <CookiesProvider>
          {children}
        </CookiesProvider>
      </body>
    </html>
  );
};

export default RootLayout;
